build:
  version: "3.0"

accounts:
  message: "Welcome to BankingApp accounts related local APIs "
  contactDetails:
    name: "Enes ?ncekara - Developer"
    email: "enesincekara@bankingapp.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345