build:
  version: "2.0"

accounts:
  message: "Welcome to BankingApp accounts related QA APIs "
  contactDetails:
    name: "enes incekara - QA Lead"
    email: "enes@incekara.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371