build:
  version: "2.0"

cards:
  message: "Welcome to BankingApp cards related QA APIs "
  contactDetails:
    name: "Enes İncekara - QA Lead"
    email: "enes@incekara.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267