build:
  version: "3.0"

loans:
  message: "Welcome to BankingApp loans related local APIs "
  contactDetails:
    name: "Enes ?ncekara- Developer"
    email: "enes@incekara.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
